name: dagger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dagger-agent:
    name: dagger-agent
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.17.0-llm.4"
          module: workspace
          verb: call
          args: test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: heal
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.17.0-llm.4"
          verb: call
          args: heal
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        if: always() && steps.test.outcome == 'failure'
